# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setStyleSheet("#title_frame{\n"
"    background-color: #606c94;\n"
"}\n"
"\n"
"#main_frame{\n"
"    border:none\n"
"}\n"
"\n"
"#menu_frame{\n"
"    background-color: pink;\n"
"    border:none;\n"
"    background-color: #8d98c3\n"
"}\n"
"\n"
"#content_frame{\n"
"    background-image: url(:/background/assets/Field_backgroundImage.jpg);\n"
"    border:none\n"
"}\n"
"\n"
"#game_frame{\n"
"    background: rgba(10,0,205,0.11);\n"
"}    \n"
"\n"
"#title_label{    \n"
"    color:white\n"
"}\n"
"\n"
"#itens_frame{\n"
"    background-color: #36ac42;\n"
"}\n"
"\n"
"#itensTitle_label{\n"
"    color:white\n"
"}\n"
"\n"
"#initConf_pushButton,\n"
"#initGame_pushButton,\n"
"#exit_pushButton{\n"
"    border-radius:5px;\n"
"    background-color: #7682ac;\n"
"    color:#fff;\n"
"    border: 1px solid #324065;\n"
"}\n"
"\n"
"#initConf_pushButton:hover,\n"
"#initGame_pushButton:hover,\n"
"#exit_pushButton:hover{\n"
"    border-radius:5px;\n"
"    background-color:#324065;\n"
"    color:#fff;\n"
"    border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"#options_frame{\n"
"    background-color: #606c94;\n"
"    border-radius:5px;\n"
"    border: 3px solid #324065\n"
"}\n"
"\n"
"#fieldConf_lineEdit,\n"
"#bombsConf_lineEdit{\n"
"    border-radius: 5px;\n"
"    border: 2px solid #324065;\n"
"}\n"
"\n"
"#fieldConf_lineEdit:hover,\n"
"#bombsConf_lineEdit:hover{\n"
"    border-radius: 5px;\n"
"    border: 2px solid #fff;\n"
"    background-color: #8d98c3\n"
"}\n"
"\n"
"#fieldConf_lineEdit:focus,\n"
"#bombsConf_lineEdit:focus{\n"
"    border-radius: 5px;\n"
"    border: 2px solid #0;\n"
"    background-color: #8d98c3\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_frame = QtWidgets.QFrame(self.centralwidget)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Jokerman")
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.title_frame)
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setLineWidth(1)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_frame = QtWidgets.QFrame(self.main_frame)
        self.menu_frame.setMaximumSize(QtCore.QSize(180, 16777215))
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout_3.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu_label = QtWidgets.QLabel(self.menu_frame)
        self.menu_label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.menu_label.setFont(font)
        self.menu_label.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_label.setObjectName("menu_label")
        self.verticalLayout_3.addWidget(self.menu_label)
        self.initConf_pushButton = QtWidgets.QPushButton(self.menu_frame)
        self.initConf_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.initConf_pushButton.setFont(font)
        self.initConf_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.initConf_pushButton.setObjectName("initConf_pushButton")
        self.verticalLayout_3.addWidget(self.initConf_pushButton)
        self.options_frame = QtWidgets.QFrame(self.menu_frame)
        self.options_frame.setMinimumSize(QtCore.QSize(0, 300))
        self.options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.options_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_frame.setObjectName("options_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.options_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.titleOptions_label = QtWidgets.QLabel(self.options_frame)
        self.titleOptions_label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.titleOptions_label.setFont(font)
        self.titleOptions_label.setAlignment(QtCore.Qt.AlignCenter)
        self.titleOptions_label.setObjectName("titleOptions_label")
        self.verticalLayout_4.addWidget(self.titleOptions_label)
        self.fieldConf_label = QtWidgets.QLabel(self.options_frame)
        self.fieldConf_label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fieldConf_label.setFont(font)
        self.fieldConf_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fieldConf_label.setObjectName("fieldConf_label")
        self.verticalLayout_4.addWidget(self.fieldConf_label)
        self.fieldConf_frame = QtWidgets.QFrame(self.options_frame)
        self.fieldConf_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.fieldConf_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fieldConf_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fieldConf_frame.setObjectName("fieldConf_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fieldConf_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fieldConf_lineEdit = QtWidgets.QLineEdit(self.fieldConf_frame)
        self.fieldConf_lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.fieldConf_lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.fieldConf_lineEdit.setText("")
        self.fieldConf_lineEdit.setReadOnly(False)
        self.fieldConf_lineEdit.setObjectName("fieldConf_lineEdit")
        self.gridLayout_2.addWidget(self.fieldConf_lineEdit, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.fieldConf_frame)
        self.bombsConf_label = QtWidgets.QLabel(self.options_frame)
        self.bombsConf_label.setMinimumSize(QtCore.QSize(0, 20))
        self.bombsConf_label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bombsConf_label.setFont(font)
        self.bombsConf_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bombsConf_label.setObjectName("bombsConf_label")
        self.verticalLayout_4.addWidget(self.bombsConf_label)
        self.bombsConf_frame = QtWidgets.QFrame(self.options_frame)
        self.bombsConf_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.bombsConf_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bombsConf_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bombsConf_frame.setObjectName("bombsConf_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.bombsConf_frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bombsConf_lineEdit = QtWidgets.QLineEdit(self.bombsConf_frame)
        self.bombsConf_lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.bombsConf_lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.bombsConf_lineEdit.setObjectName("bombsConf_lineEdit")
        self.gridLayout_3.addWidget(self.bombsConf_lineEdit, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.bombsConf_frame)
        self.label = QtWidgets.QLabel(self.options_frame)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.initGame_pushButton = QtWidgets.QPushButton(self.options_frame)
        self.initGame_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.initGame_pushButton.setFont(font)
        self.initGame_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.initGame_pushButton.setObjectName("initGame_pushButton")
        self.verticalLayout_4.addWidget(self.initGame_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 76, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.options_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 129, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.exit_pushButton = QtWidgets.QPushButton(self.menu_frame)
        self.exit_pushButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        self.exit_pushButton.setFont(font)
        self.exit_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.verticalLayout_3.addWidget(self.exit_pushButton)
        self.horizontalLayout.addWidget(self.menu_frame)
        self.content_frame = QtWidgets.QFrame(self.main_frame)
        self.content_frame.setAutoFillBackground(False)
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.game_frame = QtWidgets.QFrame(self.content_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_frame.sizePolicy().hasHeightForWidth())
        self.game_frame.setSizePolicy(sizePolicy)
        self.game_frame.setMinimumSize(QtCore.QSize(500, 500))
        self.game_frame.setMaximumSize(QtCore.QSize(500, 500))
        self.game_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.game_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.game_frame.setObjectName("game_frame")
        self.horizontalLayout_2.addWidget(self.game_frame)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.itens_frame = QtWidgets.QFrame(self.content_frame)
        self.itens_frame.setMinimumSize(QtCore.QSize(100, 60))
        self.itens_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.itens_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.itens_frame.setObjectName("itens_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.itens_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.itensTitle_label = QtWidgets.QLabel(self.itens_frame)
        self.itensTitle_label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        self.itensTitle_label.setFont(font)
        self.itensTitle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.itensTitle_label.setObjectName("itensTitle_label")
        self.verticalLayout_2.addWidget(self.itensTitle_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.countBomb_frame = QtWidgets.QFrame(self.itens_frame)
        self.countBomb_frame.setMinimumSize(QtCore.QSize(0, 30))
        self.countBomb_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.countBomb_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.countBomb_frame.setObjectName("countBomb_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.countBomb_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imgFlag_label = QtWidgets.QLabel(self.countBomb_frame)
        self.imgFlag_label.setMaximumSize(QtCore.QSize(25, 25))
        self.imgFlag_label.setText("")
        self.imgFlag_label.setPixmap(QtGui.QPixmap(":/itens/assets/flag_mode_1.png"))
        self.imgFlag_label.setScaledContents(True)
        self.imgFlag_label.setObjectName("imgFlag_label")
        self.horizontalLayout_3.addWidget(self.imgFlag_label)
        self.CountBomb_label = QtWidgets.QLabel(self.countBomb_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.CountBomb_label.setFont(font)
        self.CountBomb_label.setAlignment(QtCore.Qt.AlignCenter)
        self.CountBomb_label.setObjectName("CountBomb_label")
        self.horizontalLayout_3.addWidget(self.CountBomb_label)
        self.verticalLayout_2.addWidget(self.countBomb_frame)
        self.flag_frame = QtWidgets.QFrame(self.itens_frame)
        self.flag_frame.setMinimumSize(QtCore.QSize(80, 80))
        self.flag_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.flag_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.flag_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.flag_frame.setObjectName("flag_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.flag_frame)
        self.gridLayout_4.setContentsMargins(0, 20, 0, 20)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.flag_label = QtWidgets.QLabel(self.flag_frame)
        self.flag_label.setMaximumSize(QtCore.QSize(60, 60))
        self.flag_label.setText("")
        self.flag_label.setPixmap(QtGui.QPixmap(":/itens/assets/flag_mode_1.png"))
        self.flag_label.setScaledContents(True)
        self.flag_label.setAlignment(QtCore.Qt.AlignCenter)
        self.flag_label.setWordWrap(False)
        self.flag_label.setObjectName("flag_label")
        self.gridLayout_4.addWidget(self.flag_label, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.flag_frame)
        self.digger_frame = QtWidgets.QFrame(self.itens_frame)
        self.digger_frame.setMinimumSize(QtCore.QSize(80, 80))
        self.digger_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.digger_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.digger_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.digger_frame.setObjectName("digger_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.digger_frame)
        self.gridLayout_5.setContentsMargins(0, 20, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.digger_label = QtWidgets.QLabel(self.digger_frame)
        self.digger_label.setMaximumSize(QtCore.QSize(60, 60))
        self.digger_label.setText("")
        self.digger_label.setPixmap(QtGui.QPixmap(":/itens/assets/digger_mode_1.png"))
        self.digger_label.setScaledContents(True)
        self.digger_label.setAlignment(QtCore.Qt.AlignCenter)
        self.digger_label.setObjectName("digger_label")
        self.gridLayout_5.addWidget(self.digger_label, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.digger_frame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.infoGame_frame = QtWidgets.QFrame(self.itens_frame)
        self.infoGame_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.infoGame_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoGame_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoGame_frame.setObjectName("infoGame_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.infoGame_frame)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.InfoGame_label = QtWidgets.QLabel(self.infoGame_frame)
        self.InfoGame_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.InfoGame_label.setFont(font)
        self.InfoGame_label.setTabletTracking(False)
        self.InfoGame_label.setAcceptDrops(False)
        self.InfoGame_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.InfoGame_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.InfoGame_label.setTextFormat(QtCore.Qt.AutoText)
        self.InfoGame_label.setScaledContents(True)
        self.InfoGame_label.setAlignment(QtCore.Qt.AlignCenter)
        self.InfoGame_label.setWordWrap(False)
        self.InfoGame_label.setOpenExternalLinks(False)
        self.InfoGame_label.setObjectName("InfoGame_label")
        self.gridLayout_6.addWidget(self.InfoGame_label, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.infoGame_frame)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2.addWidget(self.itens_frame)
        self.horizontalLayout.addWidget(self.content_frame)
        self.verticalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "CAMPO MINADO EM PYTHON"))
        self.menu_label.setText(_translate("MainWindow", "Campo Minado em Python"))
        self.initConf_pushButton.setText(_translate("MainWindow", "Começar"))
        self.titleOptions_label.setText(_translate("MainWindow", "Configurações"))
        self.fieldConf_label.setText(_translate("MainWindow", "Tamanho do campo"))
        self.bombsConf_label.setText(_translate("MainWindow", "Quantidade de bombas"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.initGame_pushButton.setText(_translate("MainWindow", "Iniciar o jogo"))
        self.label_2.setText(_translate("MainWindow", "By Luis Filipe"))
        self.exit_pushButton.setText(_translate("MainWindow", "Sair"))
        self.itensTitle_label.setText(_translate("MainWindow", "ITENS"))
        self.CountBomb_label.setText(_translate("MainWindow", "0"))
        self.InfoGame_label.setText(_translate("MainWindow", "Resultado \n"
"do Jogo"))
try:
    import assets_rc
except:
    from src import assets_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
