# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\number_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(100, 100)
        Form.setMinimumSize(QtCore.QSize(40, 40))
        Form.setMaximumSize(QtCore.QSize(100, 100))
        Form.setStyleSheet("#number_label{\n"
"\n"
"    \n"
"}\n"
"\n"
"#Form{\n"
"    border:none\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.number_label = QtWidgets.QLabel(Form)
        self.number_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(50)
        font.setBold(True)
        self.number_label.setFont(font)
        self.number_label.setMouseTracking(False)
        self.number_label.setText("")
        self.number_label.setTextFormat(QtCore.Qt.PlainText)
        self.number_label.setPixmap(QtGui.QPixmap(":/modes/assets/leaf_field.png"))
        self.number_label.setScaledContents(True)
        self.number_label.setAlignment(QtCore.Qt.AlignCenter)
        self.number_label.setObjectName("number_label")
        self.gridLayout.addWidget(self.number_label, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        

        self.was_Clicked = False
        self.was_visited = False
        self.was_ClickedAsFlag = False
        self.isABomb = False
        



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

try:
    import modes_assets_rc
except:
    try:
        from widgets import modes_assets_rc
    except:
        from src.widgets import modes_assets_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
